CREATE TABLE PERSON (
    id NUMBER(10) NOT NULL,
    Date_Of_Birth DATE NOT NULL,
    Name VARCHAR2(50) NOT NULL,
    Address VARCHAR2(50) NOT NULL,
    Phone_Number VARCHAR2(10) NOT NULL,
    Email VARCHAR2(50) NOT NULL,
    CONSTRAINT person_number CHECK (LENGTH(Phone_Number) = 10),
    CONSTRAINT person_email CHECK (Email LIKE '%@%.com'),
    PRIMARY KEY (id) 
);


CREATE TABLE TRAINER (
    id NUMBER(10) NOT NULL,
    Hire_Date DATE NOT NULL,
    YEARS_OF_EXPERIENCE NUMBER(5) NOT NULL CHECK (YEARS_OF_EXPERIENCE >= 0),
    Specialization VARCHAR2(50) NOT NULL,
    Certification_Level NUMBER(5) NOT NULL CHECK (Certification_Level >= 0),
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES PERSON(id) ON DELETE CASCADE
);



CREATE TABLE EMPLOYEE (
    id NUMBER(10) NOT NULL,
    Hire_Date DATE NOT NULL,
    Salary NUMBER(10, 2) NOT NULL,
    Position VARCHAR2(50) NOT NULL,
    CONSTRAINT emp_salary CHECK (Salary >= 0),
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES PERSON(id) ON DELETE CASCADE
);



CREATE TABLE CLASS (
    Class_Id NUMBER(10) NOT NULL,
    Name VARCHAR2(50) NOT NULL,
    Timing DATE NOT NULL,
    Capacity NUMBER(5) NOT NULL,
    CONSTRAINT class_capacity CHECK (Capacity >= 0),
    PRIMARY KEY (Class_Id)
);



CREATE TABLE MEMBER (
    id NUMBER(10) NOT NULL,
    Membership_Type VARCHAR2(50) NOT NULL,
    Expiry_Date DATE NOT NULL,
    Join_Date DATE NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES PERSON(id) ON DELETE CASCADE
);



CREATE TABLE EQUIPMENT (
    EQUIPMENTID NUMBER(10) NOT NULL,
    EQUIPMENT_NAME VARCHAR2(50) NOT NULL,
    PURCHASE_DATE DATE NOT NULL,
    STATUS VARCHAR2(50) NOT NULL,
    id NUMBER(10) NOT NULL,
    PRIMARY KEY (EQUIPMENTID),
    FOREIGN KEY (id) REFERENCES MEMBER(id) ON DELETE CASCADE
);



CREATE TABLE Trains (
    TRAINER_ID NUMBER(10) NOT NULL,
    MEMBER_ID NUMBER(10) NOT NULL,
    PRIMARY KEY (TRAINER_ID, MEMBER_ID),
    FOREIGN KEY (TRAINER_ID) REFERENCES TRAINER(id) ON DELETE CASCADE,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(id) ON DELETE CASCADE
);



CREATE TABLE Holds (
    MEMBER_ID NUMBER(10) NOT NULL,
    PASSWORD NUMBER(4) NOT NULL,
    LOCKER_ID NUMBER(10) NOT NULL,
    CONSTRAINT password CHECK (LENGTH(PASSWORD) = 4),
    CONSTRAINT locker_id CHECK (LOCKER_ID >= 0),
    PRIMARY KEY (MEMBER_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(id) ON DELETE CASCADE
);



CREATE TABLE ENROLLS (
    id NUMBER(10) NOT NULL,
    Class_Id NUMBER(10) NOT NULL,
    PRIMARY KEY (id, Class_Id),
    FOREIGN KEY (id) REFERENCES MEMBER(id) ON DELETE CASCADE,
    FOREIGN KEY (Class_Id) REFERENCES CLASS(Class_Id)
);



CREATE TABLE Uses (
    MEMBER_ID NUMBER(10) NOT NULL,
    EQUIPMENTID NUMBER(10) NOT NULL,
    PRIMARY KEY (MEMBER_ID, EQUIPMENTID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(id) ON DELETE CASCADE,
    FOREIGN KEY (EQUIPMENTID) REFERENCES EQUIPMENT(EQUIPMENTID) ON DELETE CASCADE
);



CREATE TABLE SUBSCRIPTION (
    id NUMBER(10) NOT NULL,
    Name VARCHAR2(50) NOT NULL,
    Price NUMBER(10, 2) NOT NULL,
    Duration NUMBER(5) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES MEMBER(id) ON DELETE CASCADE
);



CREATE TABLE LOCKERS (
    Locker_Id NUMBER(10) NOT NULL,
    Status VARCHAR2(50) NOT NULL,
    id NUMBER(10),
    PRIMARY KEY (Locker_Id),
    FOREIGN KEY (id) REFERENCES MEMBER(id) ON DELETE CASCADE
);
